from typing import NewType

# capsule object of C board
Board = NewType('Board', object)

# row and col: start from 0 
# player: 0-empty, 1-black, 2-white

def new_board(row: int, col: int) -> Board: ...
def delete_board(board: Board) -> None: ...
def clone_board(board: Board) -> Board: ...
def get_piece(board: Board, row: int, col: int) -> int: ...
def get_qi(board: Board, row: int, col: int) -> int: ...
def get_random_qi_pos(board: Board, row: int, col: int) -> tuple[int, int]: ...
def is_valid_move(board: Board, row: int, col: int) -> bool: ...
def place_piece(board: Board, row: int, col: int) -> None: ...
def hash(board: Board) -> int: ...
def serialize(board: Board) -> bytes: ...
def deserialize(data: bytes) -> Board: ...
def does_violate_ko(board: Board, player: int, row: int, col: int, last_board: Board) -> bool: ...
